### ISSUE TITLE
local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by ambr0sial** [billythegoat356/Raven#1]
problem on Raven, when blending every images into a single one this error occurs:

Oops! An error occured: [local variable 'x' referenced before assignment]

the full thing is that:

Starting generation...

Creating directory to stock the files 'raven/universe'...
Searching for images on Google...
Downloading the images...
Shuffling the images...
Blending every image into another...

Oops! An error occured: [local variable 'x' referenced before assignment]

**Comment by billythegoat356** [comment]
yup, the program couldn't build the image, try with other keywords :)

**Comment by ambr0sial** [comment]
alright, that worked thank you, also nice profile your projects are really good.

**Comment by billythegoat356** [comment]
thx :)
